*&---------------------------------------------------------------------*
*& Report ZA020_HW3P1
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZA020_HW3P1.

TYPES: BEGIN OF AIRPSTRUCT,
         ID   TYPE SAIRPORT-ID,
         NAME TYPE SAIRPORT-NAME,
       END OF AIRPSTRUCT.


TYPES: AIRPTABLETYPE TYPE SORTED TABLE OF AIRPSTRUCT WITH UNIQUE KEY ID.

DATA: ITABLE TYPE AIRPTABLETYPE,
      WA     LIKE LINE OF ITABLE.


SELECT ID NAME FROM SAIRPORT INTO CORRESPONDING FIELDS OF TABLE ITABLE.

WA-ID = 'ETS'.
WA-NAME = 'ETSU Airport'.
INSERT WA INTO TABLE ITABLE.

DELETE TABLE ITABLE WITH TABLE KEY ID = 'HAM'.

READ TABLE ITABLE WITH TABLE KEY ID = 'BNA' INTO WA.
WA-ID = 'NAS'.
INSERT WA INTO TABLE ITABLE.
DELETE TABLE ITABLE WITH TABLE KEY ID = 'BNA'.


WRITE: 'ID', 10'Name'.
ULINE.
LOOP AT ITABLE INTO WA.
  WRITE: / WA-ID UNDER 'ID', WA-NAME UNDER 'name'.

ENDLOOP.
